### ISSUE TITLE
Project with path ':ReactAndroid' could not be found in project ':react-native-sms'

### ISSUE THREAD

**Issue by jmitch0901** [tkporter/react-native-sms#2]
Gradle build error when attempting to build on Android:

Project with path ':ReactAndroid' could not be found in project ':react-native-sms'

**Comment by tkporter** [comment]
Hey there,

Could you check out your `build.gradle` and post any lines that include `react-native-sms`?

Thanks!

**Comment by jiangsumadai** [comment]
Hi @tkporter , I get the same error when build on android.

A problem occurred evaluating project ':react-native-sms'.
Project with path ':ReactAndroid' could not be found in project ':react-native-sms'

**Comment by tkporter** [comment]
Could you both post your entire `settings.gradle` and `build.gradle` files? Those are found in the `android` directory.

**Comment by jiangsumadai** [comment]
This is my gradle files, thanks for your help.

[gradle.zip](https://github.com/tkporter/react-native-sms/files/518070/gradle.zip)

**Comment by jiangsumadai** [comment]
Entire gradle files @tkporter 

[gradle.zip](https://github.com/tkporter/react-native-sms/files/518095/gradle.zip)

**Comment by zelll** [comment]
@jiangsumadai , try this

```
diff -ur react-native-sms_bak/Android/build.gradle react-native-sms/Android/build.gradle
--- react-native-sms_bak/Android/build.gradle   2016-10-10 12:46:38.553306000 +0800
+++ react-native-sms/Android/build.gradle       2016-10-10 12:47:37.961043000 +0800
@@ -34,5 +34,5 @@
 }

 dependencies {
-    compile project(':ReactAndroid')
+    compile "com.facebook.react:react-native:+"
 }
```

**Comment by jiangsumadai** [comment]
@zelll , sorry for my late feedback of your suggestion, but it works very well, thank you.

**Comment by mikaoelitiana** [comment]
I created a PR to fix this because we don't want to edit files in node_modules for each build.
