### ISSUE TITLE
Cannot read property 'send' of undefined (Unhandled Promise Rejection)

### ISSUE THREAD

**Issue by andreatoso** [tkporter/react-native-sms#30]
Hi, I just installed this module and when I try to send a message I get this error:

`Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'send' of undefined`

If I do console.log(SendSMS) I can see that it is not undefined, so why I get this error?

**Comment by esb1** [comment]
Hey andretaoso.
I got the same error before I ran the clean command (cmd + k) in xcode and rebuilt the app.
Maybe try this if you haven't already. (react native module `SendSMS` will not be undefined, but maybe some of the native dependencies could be...)

**Comment by tkporter** [comment]
Closing, if this issue persists feel free to open

**Comment by predescu** [comment]
For anyone having this issue, if you are using Pods:
`pod install --project-directory=./ios`

**Comment by hharrari-labs** [comment]
Hello

I have the same problem on my iphone only.
I cleaned up the project and relaunched it but it always comes back.

Do you have any solutions
