### ISSUE TITLE
text messaging is not available.

### ISSUE THREAD

**Issue by ChauVV** [tkporter/react-native-sms#32]
<img width="342" alt="screen shot 2017-11-05 at 9 19 17 pm" src="https://user-images.githubusercontent.com/16476877/32415663-a0ad4718-c26f-11e7-94d2-14382d782d16.png">
on IOS, i can not send message

**Comment by lautapercuspain** [comment]
This is the message you got in the simulator, in a real device you should be fine.

**Comment by tkporter** [comment]
@ChauVV Closing for now, feel free to reopen if this is an issue on a physical device.
