### ISSUE TITLE
Send an sms in the background

### ISSUE THREAD

**Issue by lautapercuspain** [tkporter/react-native-sms#33]
Hi all, 

Very nice package. I would like to ask you guys, if you know if there´s possible to send an SMS in the background, without going to the iMassage interface, so I can keep the user on my app, all the time. Thanks for your help.

**Comment by tkporter** [comment]
Hey @lautapercuspain, I'm fairly sure that there are some restrictions imposed by iOS to prevent an app sending an SMS in the background on behalf of a user. However, I believe Android allows background SMS sending (I'm happy to accept a PR for that).

**Comment by lautapercuspain** [comment]
Hey @tkporter , Yes I´ve confirmed that there are restrictions by iOS. I´m working with iOS at the moment and I´m aware that Android is moving in a similar direction. So let´s use it, through the correct platform interface for now. ¯\_(ツ)_/¯
