### ISSUE TITLE
Malformed calls from JS, field sizes are different.

### ISSUE THREAD

**Issue by daemir** [tkporter/react-native-sms#38]
Has anyone had this issue before? I'm literally using the same code as in the description.
`SendSMS.send(
        {
          body: this.state.message,
          recipients: ['00432321312'],
          successTypes: ['sent', 'queued'],
        },
        (completed, cancelled, error) => {
          this.props.navigation.navigate('Overview');
        },
      );
`

![grafik](https://user-images.githubusercontent.com/12861760/33528265-e305ae3a-d85d-11e7-9221-fc7f51d20058.png)

**Comment by daemir** [comment]
I'm using react-native@0.50.3

**Comment by tkporter** [comment]
@daemir Could you try removing the trailing comma at the very end? I think the extra comma is posing issues with the number of arguments expected.
So instead use `SendSMS.send( { body: this.state.message, recipients: ['00432321312'], successTypes: ['sent', 'queued'], }, (completed, cancelled, error) => { this.props.navigation.navigate('Overview'); });`

**Comment by daemir** [comment]
Still facing the same issue, didn't work :/

**Comment by daemir** [comment]
Does it work for you in the newest RN version?

**Comment by daemir** [comment]
I fixed it, it was a really stupid mistake. 
Used a ``onChange`` prop instead of ``onChangeText`` on my TextInput.
