### ISSUE TITLE
Always a blank recipient is added on Android

### ISSUE THREAD

**Issue by AuroreM** [tkporter/react-native-sms#41]
Hello @tkporter 
I've got an issue with my android phone, as the lib is always adding an extra number which corresponds to a white space :
![whatsapp image 2017-12-21 at 18 05 56](https://user-images.githubusercontent.com/15011364/34266752-ae16b180-e67a-11e7-9b33-cae704df5cca.jpeg)

I think it's coming from this line, as the separator is adding a whitespace : https://github.com/tkporter/react-native-sms/blob/a80fda2c6ce0bb2979458298aab9635741d3a20f/android/src/main/java/com/tkporter/sendsms/SendSMSModule.java#L86

I will investigate further :)

**Comment by tkporter** [comment]
Hmm, thanks for finding this! It seems like the separators end up largely being manufacture-dependent, so if you find what the fix is for your phone feel free to submit a PR!

**Comment by tkporter** [comment]
Just published under v1.5.1 to include this
