### ISSUE TITLE
Will the app fail if we do not have the READ_SMS permission?

### ISSUE THREAD

**Issue by AndrewBestbier** [tkporter/react-native-sms#57]
Hi there,

I previously wanted to use this library but it became problematic because of the 'READ_SMS' permission. 

Is it possible to not include that permission at all and then use the `allowAndroidSendWithoutReadPermission` ? 

Or does the app require this as a baseline and the `allowAndroidSendWithoutReadPermission` is only used to handle the case where the user denies the permission?

**Comment by ObidosDev** [comment]
@AndrewBestbier Yes, it was my main idea for this key, and for now I am using this lib without 'READ_SMS' permission. :)

**Comment by AndrewBestbier** [comment]
Thanks @ObidosDev

**Comment by ObidosDev** [comment]
@AndrewBestbier I have got the crash on Mi MAX2, but for many others it is ok. I have got solution locally, I am going to create issue
