### ISSUE TITLE
Issue compiling on Linux - default name for Android directory (no capital ?)

### ISSUE THREAD

**Issue by efelem** [tkporter/react-native-sms#6]
Hello, 

In order to make it build on my ubuntu machine for `react-native run-android` I had to do 

`mv ./node_modules/react-native-sms/Android ./node_modules/react-native-sms/android`.

**Comment by dpiaseckisoldevelo** [comment]
Hello,
it fixed my problem:
`Cannot evaluate module react-native-sms : Configuration with name 'default' not found.`
Thanks

**Comment by tkporter** [comment]
Hi guys, thanks for the feedback. I'll change that when I get to my computer and publish it on NPM under version 1.4.1
