### ISSUE TITLE
Change project description "SMS sender with callbacks for iOS and Android"

### ISSUE THREAD

**Issue by navneet-kumar** [tkporter/react-native-sms#65]
Hi @tkporter ,

Thank's a lot for the package, could you please change the description from "SMS sender with callbacks for iOS and Android" . to "SMS sender with callbacks for Android only iOS doesn't support sending SMS programmatically"

**Comment by tkporter** [comment]
Hey @navneet-kumar, I changed the description to be a little more clear. Let me know if you think the description still doesn't represent the repo well.
