### ISSUE TITLE
Remove .git from package

### ISSUE THREAD

**Issue by sirajahmad1** [tkporter/react-native-sms#77]
**It's not letting npm to install other packages after installing react-native-sms in the project**

> npm ERR! path /var/www/html/project-name/node_modules/react-native-sms
> npm ERR! code EISGIT
> npm ERR! git /var/www/html/project-name/node_modules/react-native-sms: Appears to be a git repo or submodule.
> npm ERR! git     /var/www/html/project-name/node_modules/react-native-sms
> npm ERR! git Refusing to remove it. Update manually,
> npm ERR! git or move it out of the way first.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/user-name/.npm/_logs/2020-01-15T14_29_55_570Z-debug.log
>

**Comment by cheekw** [comment]
Bump, still having the same issue on react-native-sms 1.10.0

**Comment by tkporter** [comment]
Just pushed `1.10.1` with the fix, thank you!
