### ISSUE TITLE
Uses deprecated permission api

### ISSUE THREAD

**Issue by gulsahkandemir** [tkporter/react-native-sms#8]
Getting the following warning when we use your library:

`"PermissionsAndroid.requestPermission" is deprecated. Use "PermissionsAndroid.request" instead`

I think it's how the permission is checked in index.js.

**Comment by kiki-le-singe** [comment]
@gulsahkandemir You're right. I get this warning too.

This is the documentation about the [requestPermission method](https://facebook.github.io/react-native/docs/permissionsandroid.html#requestpermission) `"DEPRECATED - use request"`

Maybe could you do a PR?

Thanks :)

**Comment by jcharbo** [comment]
this seems to fix it
https://github.com/thejump/react-native-sms

**Comment by tkporter** [comment]
Just fixed with #11 thanks to @kfiroo

**Comment by kiki-le-singe** [comment]
Hi @tkporter

Is it possible you publish a new version on npm with this fix? Currently it's 1.4.1 and there is still "PermissionsAndroid.requestPermission".

Thanks for your time
