### ISSUE TITLE
Android app rejected due to READ_SMS permission

### ISSUE THREAD

**Issue by avenyproduction** [tkporter/react-native-sms#85]
I am creating an radio-player app, and I use react-native-sms on a contact page to allow users to send an Sms message to the radio station during live shows. 
I have declared core functionality as: Default SMS handler on Google Play Store and I understand that it is wrong, my app's core functionality is not sending SMS. I want app users to be able to open SMS app and send a message to predefined number in the radio-studio.

What can I do in order to solve this. App is approved on Apple Store.

I have received following in an email from Google:

> **Requested permissions do not match core functionality of the app**
> You declared Default SMS handler (and any other core functionality usage while default handler) as the core functionality of your app. However, after review, we found that your app does not match the declared use case(s). Learn more about permitted uses and exceptions.
> Please either:
> • Make changes to your app so that it meets the requirements of the declared core functionality or,
> • Select a use case that matches your app’s functionality
> 
> **No default handler capability**
> Default handler capability for Default SMS handler (and any other core functionality usage while default handler) was listed on your declaration form, but your app does not appear to have default handler capability. Please submit a revised Permissions Declaration Form and/or add default handler capability to your app.

**Comment by brunodlabs** [comment]
Hey @avenyproduction did you solve this? What message did you use? :)

**Comment by avenyproduction** [comment]
> Hey @avenyproduction did you solve this? What message did you use? :)

Hi, 
I have solved it using this line in /android/app/src/main/AndroidManifest.xml

<uses-permission android:name="android.permission.READ_SMS" tools:node="remove" />

**Comment by brunodlabs** [comment]
Hey @avenyproduction what line?

**Comment by sahanjith** [comment]
Anyone found a solution for this issue? Even my app got rejected because of this issue.

**Comment by ManhVuTien** [comment]
Hi @avenyproduction , what line have you added in android/app/src/main/AndroidManifest.xml?

**Comment by Frankiz123** [comment]
@hellogbg  how did you resolve this error what line you added in AndroidManifest.xml and where did you added?

**Comment by hellogbg** [comment]
> @hellogbg how did you resolve this error what line you added in AndroidManifest.xml and where did you added?

i can't recall exactly because this was long time ago, but here is my AndroidManifest.xml:

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  package="com.radio.streaming">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_SMS" tools:node="remove" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
    </application>
</manifest>
`

**Comment by Frankiz123** [comment]
thank you @hellogbg <3

**Comment by Frankiz123** [comment]
@hellogbg  i just need the send sms service so i can put this tools:node="remove"  into that and it will ok right?

**Comment by hellogbg** [comment]
> @hellogbg i just need the send sms service so i can put this tools:node="remove" into that and it will ok right?

I am also just using send sms service, so add try with this line as i did:
<uses-permission android:name="android.permission.READ_SMS" tools:node="remove" />
