### ISSUE TITLE
Error true in iOS immediately while android working

### ISSUE THREAD

**Issue by smkamranqadri** [tkporter/react-native-sms#91]
Hi,

All steps done and android is working but for iOS nothing happens, just calling the sendSMS function I receive error true and reset false.

Anyone one have issue like this or am I missing something?

**Comment by cfmitrah** [comment]
I m also having this issue any suggestion for this?

**Comment by mbellamy** [comment]
@smkamranqadri
@cfmitrah 

Looks like it works if you use it on physical device.

**Comment by smkamranqadri** [comment]
Yes, it's working on physical device but not on simulator.
