### ISSUE TITLE
SMS Callback: completed: false cancelled: falseerror: true

### ISSUE THREAD

**Issue by orsaada** [tkporter/react-native-sms#94]
hey, i run it and get this log:
SMS Callback: completed: false cancelled: falseerror: true

what could be the problem?
i followed the instructions

**Comment by sarabm** [comment]
For iOS make sure you are running on an actual device and not a simulator!

**Comment by ajaymarathe** [comment]
yes, i think so, it's look like ios simulator not supporting here :(

**Comment by tkporter** [comment]
As the others mentioned this is a limitation of the iOS simulator-- see https://stackoverflow.com/questions/9012393/testing-sms-in-the-ios-simulator

Closing for now
