### ISSUE TITLE
Doesn't work on iOS

### ISSUE THREAD

**Issue by avlonder** [tkporter/react-native-sms#96]
on iOS 14.4 (in simulator), the following code prints "true":
```
SendSMS.send({
  body: 'blabla',
  recipients: ['+32478111111'],
  successTypes: [],
  allowAndroidSendWithoutReadPermission: true
}, (completed, canceled, error) => console.log(error));
```

**Comment by ajaymarathe** [comment]
same issue here - ```console.log(error));``` error is printing ```true```. Is this package not work with ios simulator, because same code work fine on android real device :)

**Comment by tkporter** [comment]
Yeah, this is unfortunately a limitation of the simulator-- see https://stackoverflow.com/questions/9012393/testing-sms-in-the-ios-simulator

**Comment by eramudeep** [comment]
> +3247

not even working on real device
i tried adding recipients with country code, without country code, zero instead of country code
it says sms sending failed
